### ISSUE TITLE
Domain and bathymetry

### ISSUE THREAD

**Issue by mapirooznia** [team-ocean/veros#248]
Hello Dear,
1- I have provided the boundary (Domain) and bathymetry file in ".txt "format in my study area. How can I add it in Veros? 
also I have sea level and wind time series data in ."txt" format. How can I tuning them in Veros?
2- Unfortunately , I could not find the explanation about the output of the model in the website, How can I illustrate U and V components of currents and sea level?
3- Another issue that I have confused in website is which of scripts (please say the name of them) I should change to produce the physical condition of my region?
  
Thank you so much

**Comment by dionhaefner** [comment]
> Another issue that I have confused in website is which of scripts (please say the name of them) I should change to produce the physical condition of my region?

It sounds to me like you want to do a local idealized simulation. For this the `acc` setup should be appropriate (`veros copy-setup acc`). If you want something more realistic, `north_atlantic` could do, but it's also a lot more complicated.

> I have provided the boundary (Domain) and bathymetry file in ".txt "format in my study area. How can I add it in Veros?
also I have sea level and wind time series data in ."txt" format. How can I tuning them in Veros?

Veros does not have a free surface at the moment, so there is no way to incorporate sea level. You can read your text files through any Python tool you want in your setup file. Then set grid spacing and bathymetry to the appropriate values. Have a look at the setup templates to see how this is done.

> Unfortunately , I could not find the explanation about the output of the model in the website, How can I illustrate U and V components of currents and sea level?

[There is a small section on this in the docs.](https://veros.readthedocs.io/en/latest/introduction/get-started.html#reading-veros-output) For more advanced advanced post-processing I recommend you have a look at an xarray tutorial.

**Comment by dionhaefner** [comment]
> Another issue that I have confused in website is which of scripts (please say the name of them) I should change to produce the physical condition of my region?

It sounds to me like you want to do a local idealized simulation. For this the `acc` setup should be appropriate (`veros copy-setup acc`). If you want something more realistic, `north_atlantic` could do, but it's also a lot more complicated.

> I have provided the boundary (Domain) and bathymetry file in ".txt "format in my study area. How can I add it in Veros?
also I have sea level and wind time series data in ."txt" format. How can I tuning them in Veros?

Veros does not have a free surface at the moment, so there is no way to incorporate sea level. You can read your text files through any Python tool you want in your setup file. Then set grid spacing and bathymetry to the appropriate values. Have a look at the setup templates to see how this is done.

> Unfortunately , I could not find the explanation about the output of the model in the website, How can I illustrate U and V components of currents and sea level?

[There is a small section on this in the docs.](https://veros.readthedocs.io/en/latest/introduction/get-started.html#reading-veros-output) For more advanced advanced post-processing I recommend you have a look at an xarray tutorial.

**Comment by dionhaefner** [comment]
Concerning post-processing, [we now have a more in-depth tutorial in the docs](https://veros.readthedocs.io/en/latest/tutorial/analysis.html).

Looks like this is resolved for now. Feel free to re-open if you have any further issues.
