### ISSUE TITLE
Compute initial streamfunction from initial velocity

### ISSUE THREAD

**Issue by jklymak** [team-ocean/veros#271]
Not knowing the numerics, and possibly not reading the docs carefully enough, it is unclear to me how to initialize the velocities in the model.  

For a channel run, re-entrant in x, with intial velocity 0.1 m/s everywhere, no forcing, I tried do in `set_initial_conditions`: `s.u = update(vs.u, at[...], 0.1 * vs.maskU[..., None])`.  

The velocity signal only lasts for one time step, and then it is gone.  It _does_ create a small pressure perturbations that drive internal waves, but the mean flow of 0.1 m/s is immediately gone.  Conversely, the initial conditions have psi=0 everywhere, and then immediately on the next time step there is a stream function, but if the units are really m^3/s it is far too small.  

Was I to initialize psi at the beginning instead of u, or in addition to u?

**Comment by dionhaefner** [comment]
I agree that this is counter-intuitive. It may take me some time to investigate what's going on. We have an experimental surface pressure solver where this doesn't happen, so it definitely seems connected to the stream function.

**Comment by jklymak** [comment]
Cool, yes, I'm used to a surface pressure solver in the MITgcm.  Though that can be expensive and hard to parallelize.  

I'm not sure what I would do if I wanted to initialize a shear flow with non-zero barotropic flow.  Remove the barotropic and put that in as a stream function and just initialize u and v with the shear?  

Here, where I wanted a barotropic initial flow, the solution to a mean flow definitely seemed to be _not_ to specify `vs.u` and _only_ specify `vs.psi`.

**Comment by dionhaefner** [comment]
> I'm not sure what I would do if I wanted to initialize a shear flow with non-zero barotropic flow. Remove the barotropic and put that in as a stream function and just initialize u and v with the shear?

Yes that seems to be it. The streamfunction solver removes any barotropic mode from `u` and `v`, and adds it back based on `psi`.

That's a big awkward of course. I think I will pull in the first version of the surface pressure solver with linear free surface soon (identical to the MITgcm implementation). That should make things easier for you.

**Comment by jklymak** [comment]
I think, even working within the confines of the stream function solver we might consider calculating the initial steam function from the initial velocity field as an initial step.   Most of your demos start from rest, but I would expect people to be more likely to know u, v rather than psi as an initial condition?

**Comment by dionhaefner** [comment]
Yes, that's a good suggestion.
