### ISSUE TITLE
pressure solver

### ISSUE THREAD

**Issue by jklymak** [team-ocean/veros#273]
Just opening to encourage the pressure solver as an option to the stream function solver...

For the problems I do, I often want to specify the initial velocity  (see #271), and apply a momentum source to the velocity (body forcing).  The stream function formulation appears to need the initial conditions and the forcing to be explicitly separated into baroclinic and barotropic components.  I think with some work and looking at the pyOM manual I could figure out how to do that, but it might be more natural for the model to simply figure it out for me by solving the pressure equation. 

Thanks!

**Comment by dionhaefner** [comment]
[Almost done](https://github.com/jonasdelacour/veros/pull/11) :)

**Comment by jklymak** [comment]
No rush at all, this is just a fun project for me....

... and actually, I realized that I'm not sure what I said is correct.  I'd forgotten that the model is not periodic in y, so I was basing this on applying the body force to the north, and expecting a balanced flow to the east, in steady state.  But that won't happen in a channel flow because the wall sets up  a counteracting pressure gradient and the forces can be in balance with no flow set up.  

However, I suspect to get cyclic in y, you need the pressure solver anyway, so this still applies :wink:
