### ISSUE TITLE
Missing net short-wave radiation forcing in global_1deg setup?

### ISSUE THREAD

**Issue by nutrik** [team-ocean/veros#346]
It seems like there are missing `qnet` reading & assignment statements in `set_initial_conditions` routine of global_1deg setup.
There must be 2 extra lines
```
        qnet_data = self._read_forcing("q_net")
        vs.qnet = update(vs.qnet, at[2:-2, 2:-2, :], -qnet_data * vs.maskT[2:-2, 2:-2, -1, npx.newaxis])
```
according to pyOM.

**Comment by dionhaefner** [comment]
Yes, I think you are right. Are you going to make a PR?

**Comment by nutrik** [comment]
Sure, I will
