### ISSUE TITLE
Linear solver issue when parallelising VEROS

### ISSUE THREAD

**Issue by RasmusRanumHansen** [team-ocean/veros#371]
Hey all,

I have run into an issue when trying to parallelize the new version of VEROS on a cluster.
The problem arises when using the PETsc linear solver which is set as the default if you use cpu and over 1 process.
The problem is a division by zero in the _petsc_solver function in the:

rel_residual=residual_norm/rhs_norm

line. So the only way I found around this is to explicitly state what solver to use in the bash file:

export 'VEROS_LINEAR_SOLVER'='scipy'

before running the resubmit command.

The models I have tried with the same problem are: ACC_channel, ACC_basic, ACC_sector and the north Atlantic setup.

The cluster uses slurm, and this is what is written in the batch file:

#!/bin/bash -l
#SBATCH -p mycluster
#SBATCH -A myaccount
#SBATCH --job-name=veros_mysetup
#SBATCH --time=23:59:59
#SBATCH --constraint=v1
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=1
#SBATCH --threads-per-core=1
#SBATCH --exclusive

export OMP_NUM_THREADS=2

export 'VEROS_LINEAR_SOLVER'='scipy'
veros resubmit -i acc -n 1 -l  31536000\
         -c "srun --mpi=pmi2 -- veros run  acc_sector.py -b jax --float-type float32 -n 4 4" \
         --callback "sbatch veros_batch.sh"

I have also tried changing the number of taskes with no change.

The two version of VEROS I have tried are:
veros/040422_cpu_py3.9.10
veros/240322_cpu_py3.9.10

Hope this help and is the information needed,
Cheers,
Rasmus

**Comment by dionhaefner** [comment]
Reproduced and fixed on master, thanks.
