### ISSUE TITLE
How to change the sampling and output frequency of veros 1_deg model ?

### ISSUE THREAD

**Issue by Sougata18** [team-ocean/veros#473]
I want the veros 1 deg model to do the calculations on a monthly basis and also write the output on monthly frequency. What part of the code should I change ?

**Comment by dionhaefner** [comment]
https://veros.readthedocs.io/en/latest/reference/diagnostics.html

Does this help?

**Comment by Sougata18** [comment]
Actually even though I change the diagnostics it would still calculate the results on a daily basis. Is there a way to change this so that the model calculates for each month or even for each year. 
The reason I want to do this is to increase speed of calculation for a run which is of very long timescale.

**Comment by dionhaefner** [comment]
You can change the frequency of the output, but you cannot change the speed of the simulation this way. The time step is already at its maximum value for stability (30 minutes).

**Comment by Sougata18** [comment]
Okay! So the only possible way to change the simulation speed is to use more of HPC hardware resource ?

**Comment by dionhaefner** [comment]
Yes. Either that or choose a lower resolution setup.
