### ISSUE TITLE
How to add a mask file to veros and how to call in the model setup ?

### ISSUE THREAD

**Issue by Sougata18** [team-ocean/veros#484]
I have created a mask file and I want to add it to veros and call it in the model script. How can I do that ?
Thanks in advance.

**Comment by dionhaefner** [comment]
What's a mask file?

**Comment by Sougata18** [comment]
Sorry for the confusion, what I mean to say is I want to add a file just like what has been used here -   https://github.com/johannes-lohmann/rtip_veros/blob/91dc9b7d0046e1427e3ca276c84373b3c47aa8c1/global_flexible_res_freshw_hyst.py#L293 
and intriduce freshening in the specific region of interest.

**Comment by dionhaefner** [comment]
Does the recipe you linked not work for you?

**Comment by Sougata18** [comment]
The thing is I want to try this in a different setup , i.e., 4deg_global.

**Comment by dionhaefner** [comment]
Just do `np.load(mask_file)` or whatever other function you need to read the file format at hand.

**Comment by Sougata18** [comment]
Is it possible to use something like this: https://github.com/johannes-lohmann/rtip_veros/blob/91dc9b7d0046e1427e3ca276c84373b3c47aa8c1/global_flexible_res_freshw_hyst.py#L293 
where "self._get_data" method has been used to get the mask file as well as for other variables such as SST, SSS etc. in the initial condition ?

**Comment by dionhaefner** [comment]
I think that would make things unnecessarily complicated in this case, unless you also want to change the initial conditions or forcings. If you want to stick to the default values I would just load the mask and move on.

**Comment by Sougata18** [comment]
Okay, thank you for the info!

**Comment by Sougata18** [comment]
I addede the mask to a custom variable but how to interpolate it to the model grid ?
I tried something like this but not working.

`with h5netcdf.File('freshwater_mask.nc', 'r') as salt_mask_raw:`
`           salt_mask_data = salt_mask_raw.variables["freshwater_mask"]` 
`           salt_mask_data_interpolate =` `veros.tools.interpolate((salt_mask_data['freshwater_mask']['latitude'],salt_mask_data['freshwater_mask']['longitude']),
                                           salt_mask_data, vs.salt[0:1,0:1,:,:], kind='nearest')`
`            vs.freshwater = vs.freshwater.at[2:-2, 2:-2].set(salt_mask_data_interpolate)`

**Comment by Sougata18** [comment]
The problem I'm facing is that I can't access `yt` and `xt`. Could you please tell me how to access these variables ?

**Comment by dionhaefner** [comment]
>  Consider adding it to the local_variables argument of @veros_routine.

Have you tried that?

**Comment by Sougata18** [comment]
> 

Yes, but it shows something like:
` if var.ndim > 1 and coords[0].ndim == 1:`
`AttributeError: 'str' object has no attribute 'ndim'`

If you compare it to global_flexible, it can access `xt` from `vs.xt` but for global_4deg this is not the case.

**Comment by dionhaefner** [comment]
Looks like you can access it just fine. I suspect the error is because `dimensions` is a tuple of strings, but `interpolate` expects arrays of coordinates,
