### ISSUE TITLE
North Atlantic Missing assets.json

### ISSUE THREAD

**Issue by AminMoradiXL** [team-ocean/veros#519]
Dear all, 

I just began to work with this package. I want to write all my codes in python and not the terminal. So I'm using this piece of code: 
`from north_atlantic.north_atlantic import NorthAtlanticSetup, VerosSetup`
`simulation = NorthAtlanticSetup()`
`VerosSetup.setup(simulation)`
`simulation.run()`

When I read this code I get this error: 
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\project\\veros\\north_atlantic\\assets.json'`

I also get the same error from terminal as well. 
I **do not have this problem** with acc setup. 

Also, how can I **set the beginning and ending time for simulation**? I couldn't find it anywhere. 

Thank you for your help!

**Comment by AminMoradiXL** [comment]
I fixed the problem by copying all the files from [https://github.com/team-ocean/veros/tree/e5ee61900da67326c86dc6cc450ec400429ff4c3/veros/setups/north_atlantic](here) to my setup folder.

**Comment by AminMoradiXL** [comment]
I fixed the problem by copying all the files from [here](https://github.com/team-ocean/veros/tree/e5ee61900da67326c86dc6cc450ec400429ff4c3/veros/setups/north_atlantic) to my setup folder.

**Comment by dionhaefner** [comment]
Please use `veros copy-setup` for this, which takes care of populating directories properly. You are then free to import the created files somewhere else.
