### ISSUE TITLE
 Set beginning and ending time for simulation?

### ISSUE THREAD

**Issue by AminMoradiXL** [team-ocean/veros#520]
how can I **set the beginning and ending time for simulation**? I couldn't find it anywhere.

**Comment by dionhaefner** [comment]
https://veros.readthedocs.io/en/latest/reference/settings.html

See `VerosState.runlen`. Beginning is always at the origin (0).

**Comment by AminMoradiXL** [comment]
Thank you for your reply. In the veros main folder I edited the settings.py file to:
`"runlen": Setting(100.0, float, "Length of simulation in seconds"),`

didn't seem to matter. The simulation still runs for 1 year. 

Also when I try from the python code: 

```
from acc.acc import ACCSetup, VerosSetup
simulation = ACCSetup()
simulation.state.settings.runlen = 100
VerosSetup.setup(simulation)
simulation.run()

```
I get an error that says modifications are locked. `simulation.state.settings.unlock()` didn't help either. 

What I want is running this simulation for like 4000 years. What should I do?

**Comment by AminMoradiXL** [comment]
Oh I fixed it. You should change it from the `set_parameter` method of the defined class.
