### ISSUE TITLE
Unable to use the "veros create-mask" command to create mask images

### ISSUE THREAD

**Issue by Sougata18** [team-ocean/veros#595]
I am trying to use `veros create-mask` to create a mask image from `ETOPO1_Ice_g_gmt4.nc`.

But every time I am getting this error - 
```
 File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

**Comment by dionhaefner** [comment]
Is this a legacy NetCDF file by any chance? `h5netcdf` can only read NetCDF4 files.

**Comment by Sougata18** [comment]
Thanks! seems like my file was a legacy netcdf file after all. Changed it to nc4 and it worked!
